package fise.feng.com.beautifulwatchlauncher.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import fise.feng.com.beautifulwatchlauncher.entity.BTBondEntity;
import fise.feng.com.beautifulwatchlauncher.entity.MessageInfo;
import fise.feng.com.beautifulwatchlauncher.entity.NotificationEntity;
import fise.feng.com.beautifulwatchlauncher.entity.SosNumberEntity;

import fise.feng.com.beautifulwatchlauncher.dao.BTBondEntityDao;
import fise.feng.com.beautifulwatchlauncher.dao.MessageInfoDao;
import fise.feng.com.beautifulwatchlauncher.dao.NotificationEntityDao;
import fise.feng.com.beautifulwatchlauncher.dao.SosNumberEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bTBondEntityDaoConfig;
    private final DaoConfig messageInfoDaoConfig;
    private final DaoConfig notificationEntityDaoConfig;
    private final DaoConfig sosNumberEntityDaoConfig;

    private final BTBondEntityDao bTBondEntityDao;
    private final MessageInfoDao messageInfoDao;
    private final NotificationEntityDao notificationEntityDao;
    private final SosNumberEntityDao sosNumberEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bTBondEntityDaoConfig = daoConfigMap.get(BTBondEntityDao.class).clone();
        bTBondEntityDaoConfig.initIdentityScope(type);

        messageInfoDaoConfig = daoConfigMap.get(MessageInfoDao.class).clone();
        messageInfoDaoConfig.initIdentityScope(type);

        notificationEntityDaoConfig = daoConfigMap.get(NotificationEntityDao.class).clone();
        notificationEntityDaoConfig.initIdentityScope(type);

        sosNumberEntityDaoConfig = daoConfigMap.get(SosNumberEntityDao.class).clone();
        sosNumberEntityDaoConfig.initIdentityScope(type);

        bTBondEntityDao = new BTBondEntityDao(bTBondEntityDaoConfig, this);
        messageInfoDao = new MessageInfoDao(messageInfoDaoConfig, this);
        notificationEntityDao = new NotificationEntityDao(notificationEntityDaoConfig, this);
        sosNumberEntityDao = new SosNumberEntityDao(sosNumberEntityDaoConfig, this);

        registerDao(BTBondEntity.class, bTBondEntityDao);
        registerDao(MessageInfo.class, messageInfoDao);
        registerDao(NotificationEntity.class, notificationEntityDao);
        registerDao(SosNumberEntity.class, sosNumberEntityDao);
    }
    
    public void clear() {
        bTBondEntityDaoConfig.clearIdentityScope();
        messageInfoDaoConfig.clearIdentityScope();
        notificationEntityDaoConfig.clearIdentityScope();
        sosNumberEntityDaoConfig.clearIdentityScope();
    }

    public BTBondEntityDao getBTBondEntityDao() {
        return bTBondEntityDao;
    }

    public MessageInfoDao getMessageInfoDao() {
        return messageInfoDao;
    }

    public NotificationEntityDao getNotificationEntityDao() {
        return notificationEntityDao;
    }

    public SosNumberEntityDao getSosNumberEntityDao() {
        return sosNumberEntityDao;
    }

}
